name: Deploy Infraestrutura (Terraform)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform:
    name: "Terraform Build & Deploy"
    runs-on: ubuntu-latest

    # --- MUDANÇA CRÍTICA AQUI ---
    # Definindo as variáveis GLOBALMENTE para este Job.
    # Assim, o 'terraform init' já nasce sabendo a senha da AWS.
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # Variáveis do Terraform (TF_VAR)
      TF_VAR_supabase_url: ${{ secrets.TF_VAR_SUPABASE_URL }}
      TF_VAR_supabase_key: ${{ secrets.TF_VAR_SUPABASE_KEY }}
      TF_VAR_firebase_project_id: ${{ secrets.TF_VAR_FIREBASE_PROJECT_ID }}
      TF_VAR_firebase_client_email: ${{ secrets.TF_VAR_FIREBASE_CLIENT_EMAIL }}
      TF_VAR_firebase_private_key: ${{ secrets.TF_VAR_FIREBASE_PRIVATE_KEY }}
      TF_VAR_firebase_database_url: ${{ secrets.TF_VAR_FIREBASE_DATABASE_URL }}
      # Adicione o token do MP se tiver criado o segredo
      # TF_VAR_mp_access_token: ${{ secrets.TF_VAR_MP_ACCESS_TOKEN }}

    # Define o diretório padrão para onde está o main.tf
    defaults:
      run:
        working-directory: ./infra/envs/prod # <--- CONFIRME SE O CAMINHO ESTÁ CERTO!

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Este passo roda na raiz (.) para achar src/layers
      - name: Build Lambda Layer
        working-directory: .
        run: |
          echo "Instalando dependências na pasta da layer..."
          mkdir -p src/layers/python
          pip install -r src/layers/requirements.txt -t src/layers/python --upgrade

      # Agora o Init vai funcionar porque já tem as credenciais do 'env' global
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
