name: Deploy Infraestrutura (Terraform)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform:
    name: "Terraform Build & Deploy"
    runs-on: ubuntu-latest

    # Mantemos as variáveis do TF aqui, mas as da AWS vão via Action
    env:
      TF_VAR_supabase_url: ${{ secrets.TF_VAR_SUPABASE_URL }}
      TF_VAR_supabase_key: ${{ secrets.TF_VAR_SUPABASE_KEY }}
      TF_VAR_firebase_project_id: ${{ secrets.TF_VAR_FIREBASE_PROJECT_ID }}
      TF_VAR_firebase_client_email: ${{ secrets.TF_VAR_FIREBASE_CLIENT_EMAIL }}
      TF_VAR_firebase_private_key: ${{ secrets.TF_VAR_FIREBASE_PRIVATE_KEY }}
      TF_VAR_firebase_database_url: ${{ secrets.TF_VAR_FIREBASE_DATABASE_URL }}
      MELHOR_ENVIO_TOKEN: ${{ secrets.MELHOR_ENVIO_TOKEN }}

    defaults:
      run:
        working-directory: ./infra/envs/prod

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # --- A MUDANÇA MÁGICA ---
      # Configura as credenciais explicitamente antes de tudo
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
          # Importante: Desabilita o wrapper para evitar conflitos de output, as vezes ajuda
          terraform_wrapper: false

      - name: Build Lambda Layer (Amazon Linux 2 compatible)
        working-directory: .
        run: |
          mkdir -p src/layers/python
          docker run --rm --entrypoint "" -v $PWD:/var/task \
            public.ecr.aws/lambda/python:3.11 \
            pip install -r /var/task/src/layers/requirements.txt -t /var/task/src/layers/python --upgrade

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
